#!/usr/bin/env bash
# Install nginx server and configure redirection

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start

echo "Hello World!" >  /var/www/html/index.nginx-debian.html
sudo sed -i "server_name_;/ a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; "/etc/nginx/sites-evailable/default

sudo service nginx reload
