#!/usr/bin/env bash
# Configure Nginx to display a custom 404 page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo sed -i '/^}/i error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo sed -i '/^}/i location = /custom_404.html { root /var/www/html; internal; }' /etc/nginx/sites-available/default

sudo nginx -t && sudo systemctl reload nginx
