#!/usr/bin/env bash
# Displays some text, at two-second intervals, indefinitely.
# Displays "I am invincible!!!" in between each iteration.

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
